# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: alarm.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'alarm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61larm.proto\x12\x05\x61larm\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"L\n\x05\x41larm\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12(\n\x04time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x15\n\x07\x41larmId\x12\n\n\x02id\x18\x01 \x01(\x05\x32\xd2\x01\n\x07Storage\x12\x30\n\x08\x41\x64\x64\x41larm\x12\x0c.alarm.Alarm\x1a\x16.google.protobuf.Empty\x12(\n\x08GetAlarm\x12\x0e.alarm.AlarmId\x1a\x0c.alarm.Alarm\x12\x34\n\nListAlarms\x12\x16.google.protobuf.Empty\x1a\x0c.alarm.Alarm0\x01\x12\x35\n\x0b\x44\x65leteAlarm\x12\x0e.alarm.AlarmId\x1a\x16.google.protobuf.Empty2w\n\tScheduler\x12\x35\n\rScheduleAlarm\x12\x0c.alarm.Alarm\x1a\x16.google.protobuf.Empty\x12\x33\n\x0b\x46wdDueAlarm\x12\x16.google.protobuf.Empty\x1a\x0c.alarm.Alarm2H\n\x0cNotification\x12\x38\n\x10SendNotification\x12\x0c.alarm.Alarm\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'alarm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ALARM']._serialized_start=84
  _globals['_ALARM']._serialized_end=160
  _globals['_ALARMID']._serialized_start=162
  _globals['_ALARMID']._serialized_end=183
  _globals['_STORAGE']._serialized_start=186
  _globals['_STORAGE']._serialized_end=396
  _globals['_SCHEDULER']._serialized_start=398
  _globals['_SCHEDULER']._serialized_end=517
  _globals['_NOTIFICATION']._serialized_start=519
  _globals['_NOTIFICATION']._serialized_end=591
# @@protoc_insertion_point(module_scope)
