services:
  api_gateway:
    build: ../alarm_dist_sys/api_gateway
    image: api_gateway:latest
    container_name: api_gateway_RBA_locust
    ports:
      - 5000:5000
    networks:
      - alarm_dist_sys
      - frontend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 5s
      retries: 5
    depends_on:
      alarm_manager:
        condition: service_healthy
      user_manager:
        condition: service_healthy
      notification_manager:
        condition: service_healthy
      scheduler:
        condition: service_healthy
  
  alarm_manager:
    build: ../alarm_dist_sys/alarm_manager
    image: alarm_manager:latest
    container_name: alarm_manager_RBA_locust
    ports:
      - 5001:5001
    volumes:
      - ./data/alarm_manager:/app/data
    networks:
      - alarm_dist_sys
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/"]
      interval: 5s
      retries: 5
  
  user_manager:
    build: ../alarm_dist_sys/user_manager
    image: user_manager:latest
    container_name: user_manager_RBA_locust
    ports:
      - 5002:5002
    volumes:
      - ./data/user_manager:/app/data
    networks:
      - alarm_dist_sys
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/"]
      interval: 5s
      retries: 5

  notification_manager:
    build: ../alarm_dist_sys/notification_manager
    image: notification_manager:latest
    container_name: notification_manager_RBA_locust
    ports:
      - 5003:5003
    volumes:
      - ./data/notification_manager:/app/data
    networks:
      - alarm_dist_sys
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5003/"]
      interval: 5s
      retries: 5

  scheduler:
    build: ../alarm_dist_sys/scheduler
    image: scheduler:latest
    container_name: scheduler_RBA_locust
    networks:
      - alarm_dist_sys
    healthcheck:
      test: ["CMD", "pgrep", "-f", "scheduler_main.py"]
      interval: 5s
      retries: 5
    depends_on:
      notification_manager:
        condition: service_healthy
      alarm_manager:
        condition: service_healthy
  
  locust_app:
    build: .
    image: locust_app:latest
    container_name: locust_app_RBA
    ports:
      - 8089:8089
    networks:
      - frontend
    depends_on:
      api_gateway:
        condition: service_healthy

networks:
  alarm_dist_sys:
  frontend:
