services:
  node1:
    build: ./node1
    container_name: node1
  
  node2:
    build: ./node2
    container_name: node2

  node3:
    build: ./node3
    container_name: node3

  node4:
    build: ./node4
    container_name: node4

  node5:
    build: ./node5
    container_name: node5

  user:
    build: ../user
    container_name: user
    ports:
      - 8080:8080
    depends_on:
      - node1
      - node2
      - node3
      - node4
      - node5
