services:
  api_gateway:
    build: ./dist_system_nodes/api_gateway
    container_name: api_gateway
    ports:
      - 5000:5000
  
  alarm_manager:
    build: ./dist_system_nodes/alarm_manager
    container_name: alarm_manager
    ports:
      - 5001:5001
  
  scheduler:
    build: ./dist_system_nodes/scheduler
    container_name: scheduler
    ports:
      - 5002:5002

  user_manager:
    build: ./dist_system_nodes/user_manager
    container_name: user_manager
    ports:
      - 5003:5003
  
  notification_manager:
    build: ./dist_system_nodes/notification_manager
    container_name: notification_manager
    ports:
      - 5004:5004

  example_frontend_app:
    build: ./example_frontend_app
    container_name: example_frontend_app
    ports:
      - 8080:8080

