services:
  api_gateway:
    build: ./dist_system_nodes/api_gateway
    image: api_gateway:latest
    container_name: api_gateway
    ports:
      - 5000:5000
    networks:
      - dist_system_nodes
      - frontend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 5s
      retries: 5
    depends_on:
      alarm_manager:
        condition: service_healthy
      user_manager:
        condition: service_healthy
      notification_manager:
        condition: service_healthy
      scheduler:
        condition: service_healthy
  
  alarm_manager:
    build: ./dist_system_nodes/alarm_manager
    image: alarm_manager:latest
    container_name: alarm_manager
    ports:
      - 5001:5001
    networks:
      - dist_system_nodes
    volumes:
      - ./data/alarm_manager:/app/data
    environment:
      - DATABASE_URL=sqlite:///./data/alarms.db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/"]
      interval: 5s
      retries: 5
  
  scheduler:
    build: ./dist_system_nodes/scheduler
    image: scheduler:latest
    container_name: scheduler
    ports:
      - 5002:5002
    networks:
      - dist_system_nodes
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/"]
      interval: 5s
      retries: 5
    depends_on:
      notification_manager:
        condition: service_healthy
      alarm_manager:
        condition: service_healthy

  user_manager:
    build: ./dist_system_nodes/user_manager
    image: user_manager:latest
    container_name: user_manager
    ports:
      - 5003:5003
    networks:
      - dist_system_nodes
    volumes:
      - ./data/user_manager:/app/data
    environment:
      - DATABASE_URL=sqlite:///./data/users.db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5003/"]
      interval: 5s
      retries: 5

  notification_manager:
    build: ./dist_system_nodes/notification_manager
    image: notification_manager:latest
    container_name: notification_manager
    ports:
      - 5004:5004
    networks:
      - dist_system_nodes
    volumes:
      - ./data/notification_manager:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5004/"]
      interval: 5s
      retries: 5

  example_frontend_app:
    build: ./example_frontend_app
    image: example_frontend_app:latest
    container_name: example_frontend_app
    ports:
      - 8080:8080
    networks:
      - frontend
    depends_on:
      api_gateway:
        condition: service_healthy

networks:
  dist_system_nodes:
  frontend:
