services:
  api_gateway:
    build: ./api_gateway
    container_name: api_gateway
    ports:
      - 5000:5000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 5s
      retries: 5
  
  alarm_storage:
    build: ./alarm_storage
    container_name: alarm_storage
    volumes:
      - ./data/db.sqlite:/app/db.sqlite
    ports:
      - 5001:5001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/"]
      interval: 5s
      retries: 5

  scheduler:
    build: ./scheduler
    container_name: scheduler
    ports:
      - 5002:5002
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/"]
      interval: 5s
      retries: 5

  node4:
    build: ./node4
    container_name: node4

  node5:
    build: ./node5
    container_name: node5

  user:
    build: ../user
    container_name: user
    ports:
      - 8080:8080
    depends_on:
      api_gateway:
        condition: service_healthy
      alarm_storage:
        condition: service_healthy
