services:
  api_gateway:
    build: ./api_gateway
    container_name: api_gateway
    ports:
      - 5000:5000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 5s
      retries: 5
  
  alarm_database:
    build: ./alarm_database
    container_name: alarm_database
    ports:
      - 5001:5001

  alarm_processor:
    build: ./alarm_processor
    container_name: alarm_processor

  notifier:
    build: ./notifier
    container_name: notifier

  node5:
    build: ./node5
    container_name: node5

  user:
    build: ../user
    container_name: user
    ports:
      - 8080:8080
    depends_on:
      api_gateway:
        condition: service_healthy

